config/routes.rb
Rails.application.routes.draw do



  resources :unit_groups
  resources :client_applications
  resources :discount_plans
  resources :discount_plan_controls
  resources :channel_rates
  resources :discount_plan_discounts
  resources :unit_types
  resources :invoiceable_fees
  resources :units
  resources :unit_amenities	

  get 'welcome/index'
  get '/upload' => 'welcome#upload', :as => :upload
  post '/upload' => 'welcome#upload_post', :as => :upload_post

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/api_association.rb
class ApiAssociation < ApplicationRecord
	self.primary_key = "id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
	self.primary_key = "id"
end

app/models/channel_rate.rb
class ChannelRate < ApplicationRecord
	self.primary_key = "id"
	has_many :facility
	has_many :channel
	has_many :unit_group_channel_rate
	has_many :unit_group, :through => :unit_group_channel_rate
end

app/models/client_application.rb
class ClientApplication < ApplicationRecord
	self.primary_key = "id"
end

app/models/current_ledger.rb
class CurrentLedger < ApplicationRecord
	self.primary_key = "id"
end

app/models/current_tenant.rb
class CurrentTenant < ApplicationRecord
	self.primary_key = "id"
end

app/models/discount_plan.rb
class DiscountPlan < ApplicationRecord
	self.primary_key = "id"
	has_many :tenant_account_kind
	has_many :api_association
	has_many :discount_plans_connect
	has_many :discount_plan_control, :through => :discount_plans_connect
	has_many :client_application
	has_many :discount_plan_discount
	has_many :facility
	has_many :always_discount_plan_discount


end

app/models/facility.rb
class Facility < ApplicationRecord
	self.primary_key = "id"
end

app/models/invoicable_fee.rb
class InvoicableFee < ApplicationRecord
	self.primary_key = "id"
end

app/models/invoiceable_fee.rb
class InvoiceableFee < ApplicationRecord
	self.primary_key = "id"
end

app/models/scheduled_move_out.rb
class ScheduledMoveOut < ApplicationRecord
	self.primary_key = "id"
end

app/models/unit.rb
class Unit < ApplicationRecord
	self.primary_key = "id"
	has_many :unit_amenities
	has_many :channel_rate
	has_many :unit_group
	has_many :current_ledger
	has_many :current_tenant
end

app/models/unit_amenity.rb
class UnitAmenity < ApplicationRecord
	self.primary_key = "id"
end

app/models/unit_group.rb
class UnitGroup < ApplicationRecord
	self.primary_key = "id"
	has_many :scheduled_move_out
	has_many :discount_plan
	has_many :invoiceable_fee
	has_many :unit_amenities
	has_many :unit_group_channel_rate
	has_many :channel_rate, :through => :unit_group_channel_rate
	has_many :unit_type
end

app/models/unit_type.rb
class UnitType < ApplicationRecord
	self.primary_key = "id"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index


 @yeet=	EtlService.call("#{Rails.root}/data/json/KGHDSTQXYRDERRJRFBIR_units.json")

  end
  def upload
  end

  def upload_post
  	if(params["json_file"])
	  	EtlService.call(params["json_file"].tempfile)
	  	flash[:success] = "Upload Success!"
	  	render :index
	  else
	  	redirect_to :upload
	  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/unit_groups_helper.rb
module UnitGroupsHelper
end

app/helpers/unit_types_helper.rb
module UnitTypesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="container">

	<h1>Index</h1>
	<ul class="list-group">
		<li class="list-group-item"><%=	link_to  "Channel Rates", channel_rates_url %>  </li>
		<li class="list-group-item"><%=	link_to  "Client Applications", client_applications_url %>  </li>
		<li class="list-group-item"><%=	link_to  "Discount Plans", discount_plans_url %>  </li>
		<li class="list-group-item"><%=	link_to  "Discount Plan Controls", discount_plan_controls_url %>  </li>
		<li class="list-group-item"><%=	link_to  "Discount Plans Discounts", discount_plan_discounts_url %>  </li>
		<li class="list-group-item"><%=	link_to  "Invoiceable Fees", invoiceable_fees_url %>  </li>
		<li class="list-group-item"><%=	link_to  "Unit Amenities", unit_amenities_url %>  </li>
		<li class="list-group-item"><%=	link_to  "Unit Groups", unit_groups_url %>  </li>
		<li class="list-group-item"><%=	link_to  "Units ", units_url %>  </li>
		<li class="list-group-item"><%=	link_to  "Unit Types", unit_types_url %>  </li>

	</ul>
</div>

app/views/welcome/upload.html.erb
<div class="container">
<%= form_tag(upload_path, multipart: true) do %>
	<%= file_field_tag 'json_file' %>
   <%= submit_tag 'Submit' %>

 <% end %>
</div>