config/routes.rb
Rails.application.routes.draw do



  resources :unit_groups
  resources :client_applications
  resources :discount_plans
  resources :discount_plan_controls
  resources :channel_rates
  resources :discount_plan_discounts
  resources :unit_types
  resources :invoiceable_fees
  resources :units
  resources :unit_amenities	

  get 'welcome/index'
  get '/upload' => 'welcome#upload', :as => :upload
  post '/upload' => 'welcome#upload_post', :as => :upload_post

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/api_association.rb
class ApiAssociation < ApplicationRecord
	self.primary_key = "id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
	self.primary_key = "id"
end

app/models/channel_rate.rb
class ChannelRate < ApplicationRecord
	self.primary_key = "id"
	has_many :facility
	has_many :channel
	has_many :unit_group_channel_rate
	has_many :unit_group, :through => :unit_group_channel_rate
end

app/models/client_application.rb
class ClientApplication < ApplicationRecord
	self.primary_key = "id"
end

app/models/current_ledger.rb
class CurrentLedger < ApplicationRecord
	self.primary_key = "id"
end

app/models/current_tenant.rb
class CurrentTenant < ApplicationRecord
	self.primary_key = "id"
end

app/models/discount_plan.rb
class DiscountPlan < ApplicationRecord
	self.primary_key = "id"
	has_many :tenant_account_kind
	has_many :api_association
	has_many :discount_plans_connect
	has_many :discount_plan_control, :through => :discount_plans_connect
	has_many :client_application
	has_many :discount_plan_discount
	has_many :facility
	has_many :always_discount_plan_discount


end

app/models/facility.rb
class Facility < ApplicationRecord
	self.primary_key = "id"
end

app/models/invoicable_fee.rb
class InvoicableFee < ApplicationRecord
	self.primary_key = "id"
end

app/models/invoiceable_fee.rb
class InvoiceableFee < ApplicationRecord
	self.primary_key = "id"
end

app/models/scheduled_move_out.rb
class ScheduledMoveOut < ApplicationRecord
	self.primary_key = "id"
end

app/models/unit.rb
class Unit < ApplicationRecord
	self.primary_key = "id"
	has_many :unit_amenities
	has_many :channel_rate
	has_many :unit_group
	has_many :current_ledger
	has_many :current_tenant
end

app/models/unit_amenity.rb
class UnitAmenity < ApplicationRecord
	self.primary_key = "id"
end

app/models/unit_group.rb
class UnitGroup < ApplicationRecord
	self.primary_key = "id"
	has_many :scheduled_move_out
	has_many :discount_plan
	has_many :invoiceable_fee
	has_many :unit_amenities
	has_many :unit_group_channel_rate
	has_many :channel_rate, :through => :unit_group_channel_rate
	has_many :unit_type
end

app/models/unit_type.rb
class UnitType < ApplicationRecord
	self.primary_key = "id"
end

app/controllers/client_applications_controller.rb
class ClientApplicationsController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def show
     @client_application = ClientApplication.find(params[:id])
  end

  def index
     @client_applications = ClientApplication.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/client_applications_helper.rb
module ClientApplicationsHelper
end

app/helpers/unit_groups_helper.rb
module UnitGroupsHelper
end

app/helpers/unit_types_helper.rb
module UnitTypesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/client_applications/create.html.erb
<h1>ClientApplications#create</h1>
<p>Find me in app/views/client_applications/create.html.erb</p>

app/views/client_applications/destroy.html.erb
<h1>ClientApplications#destroy</h1>
<p>Find me in app/views/client_applications/destroy.html.erb</p>

app/views/client_applications/edit.html.erb
<h1>ClientApplications#edit</h1>
<p>Find me in app/views/client_applications/edit.html.erb</p>

app/views/client_applications/index.html.erb
<div class="container">
	<h1> Client Applications </h1>
	<table class="table table-hover">
		<thead>
		<tr>
			<th> Name</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
	 <% @client_applications.each do |ca| %>
	 	 <tr>
	 	 	<td><%=ca.name %> </th>
	 	 	<td> <%=	link_to  "show", client_application_path(ca) %> </th>
	 	</tr>
	 <%end %>
	</tbody>
</table>
</div>

app/views/client_applications/new.html.erb
<h1>ClientApplications#new</h1>
<p>Find me in app/views/client_applications/new.html.erb</p>

app/views/client_applications/show.html.erb
<ul>
 	<% @client_application.attributes.each do |attr, val| %>
 		<li> <%= attr %>  : <%= val %> </li>
 	<% end%>

<ul>

app/views/client_applications/update.html.erb
<h1>ClientApplications#update</h1>
<p>Find me in app/views/client_applications/update.html.erb</p>